name: CI

on:
  push:
    branches: [main]
    paths-ignore: &paths-ignore [.gitignore, LICENSE, "*.md"]
  pull_request:
    paths-ignore: *paths-ignore
  schedule:
    # Runs at 07:00 on Monday
    - cron: "0 7 * * 1"

permissions: read-all

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the codebase (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: List playbooks to test
        id: set-matrix
        run: |
          # Get range of commits
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            commit_range="origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }}"
            git fetch origin ${{ github.event.pull_request.base.ref }}
          else
            commit_range="${{ github.event.before }}...${{ github.sha }}"
          fi

          # Get list of playbooks that need to be tested
          playbooks_to_test="$(.github/workflows/list_playbooks_to_test.sh $commit_range)"

          # Convert list to json and send to GITHUB_OUTPUT
          playbooks_to_test_json="$(echo "$playbooks_to_test" | yq 'split(" ")' -o=json | yq)"
          echo "matrix=$playbooks_to_test_json" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Install lint dependencies
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint tasks/ playbooks/
        env:
          FORCE_COLOR: "1"

  molecule:
    needs: [generate-matrix, lint]
    runs-on: ubuntu-latest
    strategy:
      # Doesn't stop all jobs if a single job fails
      fail-fast: false
      matrix:
        playbook: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      # Fails without "requirements.txt" for some reason
      # https://github.com/marketplace/actions/build-and-setup-python#no-file-in--matched-to-requirementstxt-or-pyprojecttoml-make-sure-you-have-checked-out-the-target-repository
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Molecule tests
        run: molecule test -- --diff -v
        env:
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
