name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the codebase (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: List playbooks to test
        id: set-matrix
        shell: bash
        run: |
          set -euxo pipefail

          # Get range of commits
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            range="origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }}"
            git fetch origin ${{ github.event.pull_request.base.ref }}
          else
            range="${{ github.event.before }}...${{ github.sha }}"
          fi

          # List of all playbooks
          all_playbooks="$(find playbooks/ -name '*.yml' -type f)"

          # If CI or molecule conf is changed, test all playbooks; otherwise, tests only changed ones
          if [ -n "$(git diff --name-only $range -- .github/workflows/)" ] || [ -n "$(git diff --name-only $range -- molecule/)" ]; then
            playbooks_to_test="$all_playbooks"
          else
            playbooks_to_test="$(git diff --name-only $range -- playbooks/*.yml)"

            # If "tasks/add_debian_repo.yml" is changed, also add playbooks that include it in the test list
            if [ -n "$(git diff --name-only $range -- tasks/add_debian_repo.yml)" ]; then
              playbooks_to_test="$playbooks_to_test $(grep --files-with-matches 'include_tasks.*tasks/add_debian_repo.yml' $all_playbooks)"
            fi

            # If "tasks/add_asdf_plugins_and_tools.yml" is changed, also add playbooks that include it in the test list
            if [ -n "$(git diff --name-only $range -- tasks/add_asdf_plugins_and_tools.yml)" ]; then
              playbooks_to_test="$playbooks_to_test $(grep --files-with-matches 'include_tasks.*tasks/add_asdf_plugins_and_tools.yml' $all_playbooks)"
            fi
          fi

          # Remove duplicate entries, format and convert to compact json
          playbooks_to_test_json="$(echo "$playbooks_to_test" \
            | tr ' ' '\n' \
            | sort -u \
            | xargs \
            | tr -d '\n' \
            | jq -R -s -c 'split(" ")')"

          # Send to GITHUB_OUTPUT
          echo "matrix=$playbooks_to_test_json" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Install lint dependencies
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint tasks/ playbooks/
        env:
          FORCE_COLOR: "1"

  molecule:
    needs: [generate-matrix, lint]
    runs-on: ubuntu-latest
    strategy:
      # Doesn't stop all jobs if a single job fails
      fail-fast: false
      matrix:
        playbook: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      # Fails without "requirements.txt" for some reason
      # https://github.com/marketplace/actions/build-and-setup-python#no-file-in--matched-to-requirementstxt-or-pyprojecttoml-make-sure-you-have-checked-out-the-target-repository
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Molecule tests
        run: MOLECULE_PLAYBOOK=${{ matrix.playbook }} molecule test -- --diff -v
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
